### ISSUE TITLE
Combining references and authors groups? 

### ISSUE THREAD

**Issue by jhkennedy** [vweevers/common-changelog#18]
:wave: I've started migrating from Keep A Changelog to Common Changlelog and I have to say I really like it thus far.

However, I find it a little hard to read with references and authors in separate parentheticals:
```md
- Fix infinite loop ([#194](https://github.com/owner/name/issues/194)) (Alice Meerkat)
```

Would you consider allowing references and authors to be combined? I think a form like this would be a little bit more readable:
```md
- Fix infinite loop ([#194](https://github.com/owner/name/issues/194); Alice Meerkat)
```

I've used  a semi-colon here so that multiple references and authors could be provided:
```md
- Fix infinite loops ([#194](https://github.com/owner/name/issues/194), [#195](https://github.com/owner/name/issues/195); Alice Meerkat, Milly Moose, Billy Goat)
```

**Comment by vweevers** [comment]
Hi! The semicolon feels a bit unnatural, I think because it's not combining complete sentences here. I would have no objection to combining using commas though:

```md
- Fix infinite loop ([#194](https://github.com/owner/name/issues/194), Alice Meerkat)
```

It would have to be opt-in indeed, because separate parentheticals (I learned a new word) simplify automation. E.g. if you take a commit message that may already have references, and you add authors. But as a reader it doesn't matter to me, either is fine.

**Comment by jhkennedy** [comment]
Awesome, thank you for the response!

> I learned a new word

:tada: [One of the lucky 10,000!](https://xkcd.com/1053/) 

> The semicolon feels a bit unnatural, I think because it's not combining complete sentences here. I would have no objection to combining using commas though:

Grammatically, it's common to use a semicolon to separate lists with internal punctuation (lists of lists), e.g.:
https://www.scribbr.com/language-rules/semicolons/

I agree that when there is a singular reference and a singular author, the comma makes the most sense. However, the semi-colon would make more sense if there were multiple references and/or multiple authors to keep the group separate. 

> It would have to be opt-in indeed because separate parentheticals (I learned a new word) simplify automation

Always using the semi-colon should make grouping automatable, as you can still easily separate the references from the authors. That said, I agree with opt-in.

**Comment by vweevers** [comment]
Convinced! And between Milly Moose and Billy Goat I liked Milly Moose the best 😄: https://github.com/vweevers/common-changelog/pull/19.

**Comment by vweevers** [comment]
Deployed to the website. Thanks for the feedback!
