### ISSUE TITLE
Clicking on sections does not work

### ISSUE THREAD

**Issue by paulrberg** [vweevers/common-changelog#7]
## Description

Love this initiative! Just want to report a minor issue.

I was reading your [website](https://common-changelog.org/) and I noticed that when clicking on sections in the table of contents, the browser view does not not get updates. That is, the view is not scrolled down or up to the location of the section that I clicked.

Here's a screen recording:

https://user-images.githubusercontent.com/8782666/158018832-edf1a715-7a03-44ef-82bc-a508dd52c022.mov

## Environment

- macOS@12.2.1
- Google Chrome v99.0.4844.51

**Comment by vweevers** [comment]
Thanks for reporting! This is a bug [somewhere in the code](https://github.com/vweevers/common-changelog/blob/main/website/build.mjs) that generates HTML from markdown. Current output is:

```html
<h3 id="24change-group">...</h3>
```

Should be:

```html
<h3 id="24-change-group">...</h3>
```
